.de Id
.ds Rv \\$3
.ds Dt \\$4
.ds iD \\$3 \\$4 \\$5 \\$6 \\$7
..
.Id $Id: d_crset.3,v 1.1.1.1 1999/09/30 04:45:50 kaz Exp $
.ds r \s-1TYPHOON\s0
.if n .ds - \%--
.if t .ds - \(em
.TH D_CRSET 1 \*(Dt TYPHOON
.SH NAME
d_crset \- set the current record
.SH SYNOPSIS
.B #include <typhoon.h>
.br

\fBd_crset(DB_ADDR *\fPaddr\fB)
.SH DESCRIPTION
\fBd_crset\fP sets the current record. If no database is currently open,
\fBS_NOCD\fP is returned.
.SH DIAGNOSTICS
The status code returned by the function is also stored in the global
variable \fIdb_status\fP.
.TP
.B S_OKAY
Operation successful.
.TP
.B S_NOCD
There is no current database.
.TP
.B S_INVADDR
The specified address is invalid.
.SH CURRENCY CHANGES
The record at the specified database address becomes the current record.
.SH IDENTIFICATION
Author: Thomas B. Pedersen.
.br
Copyright (c) 1994 Thomas B. Pedersen.
.SH "SEE ALSO"
d_crget(1)

