.de Id
.ds Rv \\$3
.ds Dt \\$4
.ds iD \\$3 \\$4 \\$5 \\$6 \\$7
..
.Id $Id: d_keyread.3,v 1.1.1.1 1999/09/30 04:45:51 kaz Exp $
.ds r \s-1TYPHOON\s0
.if n .ds - \%--
.if t .ds - \(em
.TH D_KEYREAD 1 \*(Dt TYPHOON
.SH NAME
d_keyread \- read the most recently found key
.SH SYNOPSIS
.B #include <typhoon.h>
.br

\fBd_keyread(void *\fPbuf\fB)
.SH DESCRIPTION
\fBd_keyread\fP copies the contents of the most recently accessed key
field specified by \fIfieldid\fP
into the buffer \fIbuf\fP. This can be used to determine the contents
of a key's fields without actually reading the record.
.br
.SH DIAGNOSTICS
The status code returned by the function is also stored in the global
variable \fIdb_status\fP.
.TP
.B S_OKAY
Operation successful.
.TP
.B S_NOCD
There is no current database.
.TP
.B S_NOCR
There is no current record.
.TP
None.
.SH EXAMPLE
/* Find the smallest customer name */
.br

#include <typhoon.h>
.br

if( d_keyfrst(CUSTOMER_NAME) == S_OKAY )
.br
{
.br
	char name[30];
.br
    d_keyread(name);
    printf("Name %s\\n", name);
.br
}
.SH IDENTIFICATION
Author: Thomas B. Pedersen.
.br
Copyright (c) 1994 Thomas B. Pedersen.
.SH "SEE ALSO"
d_recread(1), d_crread(1)
